### ISSUE TITLE
Function.prototype.displayName needs polyfill

### ISSUE THREAD

**Issue by behnammodi** [behnammodi/polyfill#11]

**Comment by github-nilsson** [comment]
I don't think it is possible to make a polyfill for, as it is the formatting code that displays JavaScript functions that has to be expanded, not any of the code within the context of the web page.

**Comment by github-nilsson** [comment]
Function.prototype.name however could be possible in most cases. Basically a getter that returns the function name you get from running (this+""). It will however not be able to figure out the assigned variable name for anonymous functions.

**Comment by behnammodi** [comment]
So it can be possible for some of the fucntions? yes?

**Comment by github-nilsson** [comment]
Yes. Something like this probably.

```js
var rx = /function\ (.+)\(/;
Object.defineProperty(Function.prototype, "name", {
  get: function() {
    var match = rx.exec(this+"");
    return match.length===2 ? match[1] : "";
  },
});
```

**Comment by behnammodi** [comment]
Awesome, would you like to create PR?
