### ISSUE TITLE
Array.prototype.flat should take "depth" argument

### ISSUE THREAD

**Issue by noppa** [behnammodi/polyfill#18]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat):

> **Parameters**
depth Optional
    The depth level specifying how deep a nested array structure should be flattened. Defaults to 1. 

```javascript
const arr2 = [0, 1, 2, [[[3, 4]]]];

console.log(arr2.flat(2));
// expected output: [0, 1, 2, [3, 4]]
```
with this polyfill, the result of the above example is actually `[0, 1, 2, 3, 4]`. The current implementation doesn't take a "depth" parameter and seems to always act as if `depth=Infinity`.

**Comment by behnammodi** [comment]
@noppa I will fix it.

**Comment by behnammodi** [comment]
@github-nilsson Could you help me

**Comment by behnammodi** [comment]
@noppa Do you interested in solving this bug by a PR?

**Comment by noppa** [comment]
Sure, I can take a look

**Comment by behnammodi** [comment]
Thank you 🙏🏻
